- quantecon/matrix_eqn.py
- quantecon/tests/test_matrix_eqn.py
Minor issue with the discrete Lyapunov solver via doubling: a missing complex conjugation operation causes incorrect results if the input is complex. The unit test shows the failure in the current setup and passes with the fix.
> FIX: Discrete Lyapunov with complex input

- setup.py
Adding a new DESCRIPTION, LONG_DESCRIPTION, LICENSE and CLASSIFIERS for the PYPI page. 
Using setup tools this should automatically build a new PYPI README.
To view the markdown we may want to submit to pypi test server first.  
This closes issue #85
> Adding more information for the PYPI README

- quantecon/models/__init__.py
@jstac @spencerlyon2 
I noticed when I upgraded to the new release of `quantecon` that
```
from quantecon.models import solow
```
command that had been working on my machine was no longer working.  Not sure exactly what the problem is. After checking the `__init__.py` file in the `models` module I noticed that `solow` was not in the module's name space.  This PR should fix that problem. Again, everything is working on my machine but it would be good to get independent verification.
> Fixed import statements in __init__.py to include solow module.

- quantecon/models/__init__.py
@jstac 
This PR fixes the import statement for the `solow` module. Note that I am able to import `quantecon` cleanly from my root directory (i.e., outside the repo)...
```python
Davids-MacBook-Pro:~ drpugh$ source activate quantecon-dev
discarding /Users/drpugh/anaconda/bin from PATH
prepending /Users/drpugh/anaconda/envs/quantecon-dev/bin to PATH
(quantecon-dev)Davids-MacBook-Pro:~ drpugh$ ipython
Python 2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:37:34) 
Type "copyright", "credits" or "license" for more information.
IPython 2.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick …
```
> Fixed imports for solow module...again!

- quantecon/compute_fp.py
This adds a bit prettier printing scheme to compute fixed point.
It might belong somewhere else in the project as it can be used in any iterative algorithm.
Perhaps we should lump this and @albop's timer code into a `util.py` file or something similar?
> ENH: added formatting to iteration printing

- docs/source/conf.py
- rtd-pip-requirements.txt
This PR makes some minor adjustments to allow the ``readthedocs`` to compile properly. The ``solow`` module's use of ``sympy`` created issues for the ``sympy`` mock. 
Add ``sympy`` to ``rtd`` requirements
Remove ``sympy`` from mock. 
http://quanteconpy.readthedocs.org/en/solow-rtd-fix/index.html
Notes
1. ``qe_apidoc`` still needs to be updated to reflect the presence of the ``solow`` module.
> Adjust mock and environment requirements for proper compilation on RTD

- quantecon/kalman.py
Getting ready to present the library. Wanted to show this class -- needed it to be pristine :)
> STY: pep8ified kalman.py

- quantecon/markov/core.py
- quantecon/markov/tests/test_core.py
This follows the discussions in #146.
(I hope I did "rebase" in the right way.)
0. I propose to change the `simulate` method as `simulate(ts_length, init=None, num_reps=None, random_state=None)`; see https://github.com/QuantEcon/QuantEcon.py/issues/146#issuecomment-109540676.
* `init` now does not accept a distribution; see https://github.com/QuantEcon/QuantEcon.py/issues/146#issuecomment-117006253 and https://github.com/QuantEcon/QuantEcon.py/issues/146#issuecomment-117425074.
0. `random_state` option is added to `MarkovChain.simulate` (not to `MarkovChain.__init__`).
0. [`test_mc_sample_path`](https://github.com/QuantEcon/QuantEcon.py/blob/3ba9f53e3064385f2f852b820fa3ff2cef5a7083/quantecon/markov/tests/test_core.py#L259) is added with `random_state` specified.
> MarkovChain.simulate API change; random_state option added

- quantecon/graph_tools.py
- quantecon/markov/core.py
- quantecon/markov/gth_solve.py
- quantecon/markov/random.py
- quantecon/markov/tests/test_core.py
- quantecon/markov/tests/test_random.py
- quantecon/tests/test_graph_tools.py
Extend `MarkovChain` to accept sparse matrix input.
Everything was almost straightforward, except the computation of stationary distributions:
* In passing the matrix to `gth_solve`, the sparse matrix input is converted to a dense matrix. If the input is a large matrix, this will require a large amount of memory accordingly. Extending `gth_solve` to sparse matrices is highly nontrivial, due to *fill-in*.
> MarkovChain: Sparse matrix support

- quantecon/markov/ddp.py
- quantecon/markov/tests/test_ddp.py
The current code sorts `s_indices` and `a_indices`, whether or not they are already sorted. This PR checks whether they are already sorted (and if they are, does not sort them again).
It also contains two other small corrections (too small for independent PRs).
> DiscreteDP refactoring

- quantecon/random/utilities.py
Modify `probvec` to make memory consumption smaller.
* Remove a temporary array.
* Replace `np.diff`, which was a big bottleneck, with a custom routine `_diff`, which uses Numba.
> probvec: Use less memory

- docs/source/conf.py
- docs/source/markov.rst
- docs/source/models.rst
- docs/source/models/arellano_vfi.rst
- docs/source/models/lake.rst
- docs/source/models/uncertainty_traps.rst
- docs/source/tools.rst
- docs/source/util.rst
- docs/source/util/common_messages.rst
- docs/source/util/external.rst
- docs/source/util/timing.rst
Update importation of ``ipython_directive`` to be imported from Ipython project rather than local version. 
This also updates the ``rst`` files from the latest local build of html files.
> Fix readthedocs

- quantecon/markov/core.py
- quantecon/markov/tests/test_core.py
* Address #190: Check that `init` is an instance of `numbers.Integral`
* Check that `init` is in `{0, ..., n-1}` or `{-n, ..., -1}`
> Fix: MarkovChain.simulate

- quantecon/random/utilities.py
> sample_without_replacement refactored

- quantecon/markov/ddp.py
Sorry to make such a small fix.
* Looking at the [documentation](http://quanteconpy.readthedocs.org/en/latest/markov/ddp.html) of `DiscreteDP`, I realized that I had forgotten to add `r` at the beginning of the docstring that contains math expressions... An `r` is added now, and some minor edits are made in docstrings.
* Wrong indentation is fixed.
> DiscreteDDP: minor fix in docstring and pep8 compliance

- quantecon/kalman.py
In the stationary coefficients for Kalman filter, update was being done with
```
P = Matrix
...
dot(P, P)
```
but this gives us P, P^2, P^4... instead of P, P^2, P^3...
Opening PR so John can make it prettier if he would like.
> Fix P update in stationary coefficients.

- .travis.yml
Try to resolve "conda: command not found" as in #204.
Searching around in GitHub, I found [this](https://github.com/NVIDIA/caffe/pull/67), which I copy here. See what happens...
> TRAVIS: set destination path for miniconda

- quantecon/markov/tests/test_random.py
- quantecon/random/utilities.py
Handle the case of `k=1` separately as in the [Julia version](https://github.com/QuantEcon/QuantEcon.jl/pull/80).
> BUG: Fix bug in probvec

- .travis.yml
- setup.py
This PR checks compatibility with Python ``3.5`` and makes necessary adjustments. 
Status: **Not** yet ready to merge
> Adjust Travis-CI to run in python 3.5 and adjust pip classifiers

- quantecon/__init__.py
Fixes QuantEcon/QuantEcon.notebooks#21.
(`models/career.py` used to have `from quantecon.distributions import BetaBinomial` which made `quantecon.distributions` importable without `from . import distributions` in `__init__.py`, but `models` has now gone.)
> Add `distributions` to quantecon/__init__.py

- quantecon/lqcontrol.py
- quantecon/lss.py
I don't know if there was an original reason for using `"float32"` in our converter functions, but it might be nice to use the system default. Opening this to see what people think -- I'd rather use system default.
```
In [7]: x = np.random.randn(25)
In [8]: np.asarray(x, dtype="float32").dtype
Out[8]: dtype('float32')
In [9]: np.asarray(x, dtype="float64").dtype
Out[9]: dtype('float64')
In [10]: np.asarray(x, dtype="float").dtype
Out[10]: dtype('float64')
```
> Change converter functions to use default float

- docs/qe_apidoc.py
- docs/source/game_theory.rst
- docs/source/game_theory/normal_form_game.rst
- docs/source/index.rst
- quantecon/__init__.py
- quantecon/game_theory/__init__.py
- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/tests/test_normal_form_game.py
- setup.py
This PR adds code on base classes for game theory tools, `Player` and `NormalFormGame` (written with help from my previous RA @kusanot): see [this notebook](http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/game_theory/game_theory_py.ipynb) for demonstration.
(Applications to learning/evolutionary dynamics models will be submitted with other PRs.)
* Created a new directory `game_theory`, and
* edited `docs/qe_apidoc.py` accordingly.
> Add game_theory.normal_form_game

- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/tests/test_normal_form_game.py
Relatively minor changes:
1.
`NormalFormGame` now requires the `Player` instances to be homogeneous in `dtype` (as in the [Julia version](https://github.com/QuantEcon/QuantEcon.jl/pull/95)).
2.
`NormalFormGame.__getitem__` returns an `ndarray` of the common `dtype` (previously, it was `list`).
3.
`Player.__repr__` has been changed:
```python
>>> player = Player([[4, 0], [3, 2]])
>>> player
Player([[4, 0],
[3, 2]])
```
(`NormalFormGame.__repr__` kept unchanged. Constructing a payoff profile array is costly, so it is printed by an explicit call of `print`.)
> Changes in normal_form_game

- .travis.yml
1. Use a full anaconda environment to have the same environment as users. This might slow down the setup phase - and if so we can restore to a minimal environment.
> Adjustments to cleanup travis CI

- docs/qe_apidoc.py
- docs/source/game_theory.rst
Simple update to improve the title of the game theory module in the documentation.
``Game_theory`` to ``Game theory``
> Update name of Game Theory for cleaner look

- quantecon/markov/ddp.py
This is to remove `num_actions` from `DiscreteDP`, following my argument in https://github.com/QuantEcon/QuantEcon.jl/pull/94#issuecomment-175002454.
And also remove a small inefficiency in `modified_policy_iteration`.
> Drop `num_actions` from DiscreteDP

- quantecon/markov/__init__.py
- quantecon/markov/ddp.py
- quantecon/markov/tests/test_ddp.py
> DiscreteDP: Allow beta=1

- quantecon/graph_tools.py
- quantecon/markov/core.py
- quantecon/markov/tests/test_core.py
- quantecon/tests/test_graph_tools.py
> Add states/nodes to MarkovChain/DiGraph

- quantecon/markov/approximation.py
- quantecon/markov/tests/test_approximation.py
This is an obvious change, now that we have state values.
Modified tests appropriately.
> Modified tauchen to return a MarkovChain instance that stores both states and transitions

- quantecon/markov/core.py
- quantecon/markov/tests/test_core.py
I forgot to change `recurrent_classes` to `recurrent_classes_indices`.
> MarkovChain: Bug fix in _compute_stationary with state_values

- quantecon/random/tests/test_utilities.py
- quantecon/random/utilities.py
This is to modify `probvec` to use [`guvectorize`](http://numba.pydata.org/numba-doc/dev/user/vectorize.html#the-guvectorize-decorator) with `target='parallel'`.
(`probvec` is mainly used to generate samples of `MarkovChain` or `DiscreteDP`.)
* Use of `guvectorize` simplifies the logic slightly; we don't need to explicitly write the outer loop.
* This version puts `sort()` in a jitted loop with nopython mode, the bottleneck of [the current `probvec`](https://github.com/QuantEcon/QuantEcon.py/blob/05d72ce1cb6a24317838909b019c9f711ccad61f/quantecon/random/utilities.py#L50).
* [Sorting by Numba may be slower than Numpy](http://numba.pydata.org/numba-doc/0.25.0/reference/numpysupported.html#other-methods), but with `target='parallel'` this version is faster than the current version on …
> probvec: Use guvectorize with target='parallel'

- quantecon/version.py
- setup.py
This PR updates to version 0.3.3 which includes
1. Remove ``python2.7`` classifiers as it is a ``python3.5+`` project. 
2. Migrates ``sa_indices`` to be a utility function for the markov submodule
3. Updates ``probvec`` to include a multi-core parallel option using numba infrastructure in ``quantecon/random/utilities.py``.
This includes some minor house cleaning to incorporate the package in ``conda-forge``
> Update to version 0.3.3

- quantecon/arma.py
- quantecon/matrix_eqn.py
This PR removes the warning supression from `arma.py` and `matrix_eqn.py`.
**TODO:** The next step is to fix the underlying cause of the warning.
> Remove warnings supression as noted by Issue #229

- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/tests/test_normal_form_game.py
Make `payoff_array`'s C contiguous when when a `payoff_profile_array` is passed to `NormalFormGame`, in order for Numba not to complain.
> Player, NormalFormGame: Make `payoff_array`'s C contiguous

- quantecon/game_theory/__init__.py
- quantecon/game_theory/random.py
- quantecon/game_theory/tests/test_random.py
* `random_game`: sampled from uniform
* `covariance_game`: sampled from multivariate normal with a covariance parameter
> game_theory: Add random game generators

- quantecon/game_theory/__init__.py
- quantecon/game_theory/support_enumeration.py
- quantecon/game_theory/tests/test_support_enumeration.py
Implement "support enumeration", a simple and inefficient algorithm that computes all mixed-action Nash equilibria of a non-degenerate 2-player game.
1. Jit-compiled if Numba >= 0.28 is installed. Fallback to a non-jit version otherwise.
2. The algorithm is to check for all the size-k support pairs for k = 1, ..., min(m, n) whether there is a Nash equilibrium with the given support by solving a linear equation of the indifference conditions, where m and n are the numbers of actions of players 0 and 1, respectively. Note that if m = n, there are (2n choose n - 1) such pairs (for example, 184,755 pairs if n = 10).
3. In solving the linear equation in [`_indiff_mixed_action`](https://github.com/QuantEcon/QuantEcon.py/blob/2926e17cdbc6026b39140f32810402de27501c16/quantecon/game_theory/support_ …
> game_theory: Add support_enumeration

- quantecon/game_theory/__init__.py
- quantecon/game_theory/lemke_howson.py
- quantecon/game_theory/tests/test_lemke_howson.py
Implement the Lemke-Howson algorithm.
1. Implemented with floating point arithmetic. I also tried integer pivoting (as described in von Stengel 2007), but overflow easily occurs with `np.int64`. In a Julia version we may want to try with `BigInt`.
2. The `full_output` option mimics root finding routines in scipy such as [`brentq`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.brentq.html).
2. `sicpy.optimize.OptimizeResult` is used again as in `DPSolveResult` (but with `sort` in `__repr__`). Maybe we should put it in `util` for example, to be inherited by `DPSolveResult` and `NashResult` here to get rid of duplicates in the code.
Cc: @kevtimova @ArnavSood @shizejin
> game_theory: Add lemke_howson

- quantecon/game_theory/__init__.py
- quantecon/game_theory/pure_nash.py
- quantecon/game_theory/tests/test_pure_nash.py
Based on #266.
Add a function `pure_nash_brute` to find all pure nash equilibria of a normal form game using brute force method. 
For example, consider the Prisoners' Dilemma game. 
```
>>> PD_bimatrix = [[(1, 1), (-2, 3)],
...                [(3, -2), (0, 0)]]
>>> g_PD = NormalFormGame(PD_bimatrix)
>>> pure_nash_brute(g_PD)
[(1, 1)]
```
Mainly referred to [Tools for Game Theory](http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/game_theory_py.ipynb). @oyamad
> Add brute force method for finding pure nash equilibria.

- .gitignore
- quantecon/compute_fp.py
- quantecon/game_theory/__init__.py
- quantecon/game_theory/lemke_howson.py
- quantecon/game_theory/mclennan_tourky.py
- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/tests/test_lemke_howson.py
- quantecon/game_theory/tests/test_mclennan_tourky.py
- quantecon/game_theory/utilities.py
- quantecon/tests/test_compute_fp.py
Based on #268.
Implement the fixed point computation algorithm by McLennan and Tourky "[From Imitation Games to Kakutani](http://cupid.economics.uq.edu.au/mclennan/Papers/kakutani60.pdf)."
* It computes an approximate fixed point of a function that satisfies the assumptions of Brouwer's fixed point theorem, i.e., a continuous function that maps a compact convex set to itself.
* For contraction mappings, the generated sequence is the same as that by function iteration, so for those functions there is no improvement.
An example from McLennan and Tourky (Example 4.6):
```py
def f(x, M, c):
return -np.arctan(np.dot(M, (x - c)**3)) + c
n = 500
tol = 1e-5
max_iter = 200
c = np.random.standard_normal(n)
np.random.seed(0)
M = np.abs(np.random.standard_normal(size=(n, n)))
x_init = …
```
> Implement the "imitation game algorithm" by McLennan-Tourky

- .travis.yml
Number 0.30.0 has been released.
Will close #269.
> TRAVIS: Remove `=0.28.1` from conda install numba

- quantecon/__init__.py
I suggest we upgrade the useful utilities `tic`, `toc` and `tac` to the top level namespace.
@mmcky If you agree would you mind to test first and then merge?
> upgraded tic, tac and toc to top level

- quantecon/util/notebooks.py
- quantecon/util/tests/test_file.md
- quantecon/util/tests/test_notebooks.py
@oyamad Once this is merged -- unfortunately this will break the notebook. But I think you guys are right -- this will be clearer to use.
@cc7768 Is this what you mean re issue #278?
> improve dependency fetcher with clearer parameters

- quantecon/game_theory/support_enumeration.py
Remove `cache=True` in a jitted function for `support_enumeration`.
The kernel dies if a notebook with `support_enumeration` is executed by `Run All`. After this event, Python always dies with `support_enumeration` with a message
```
LLVM ERROR: Program used external function '_numba.targets.arraymath.np_any.<locals>.flat_any$26.array(bool,_1d,_C)' which could not be resolved!
```
This does not happen once `cache=True` is removed from `_indiff_mixed_action`.
> FIX: support_enumeration: Disable cache in _indiff_mixed_action

- rtd-environment.yml
this PR removes the version of quantecon from rtd-environment so that it loads the latest version. 
- check if this fixes our current rtd issue with rendering some lectures.
> remove specific version of quantecon from rtd environment

- quantecon/__init__.py
- quantecon/markov/__init__.py
- quantecon/markov/approximation.py
- quantecon/markov/tests/test_approximation.py
> Add rouwenhorst method for approx AR(1) with MC

- quantecon/cartesian.py
- quantecon/compute_fp.py
- quantecon/game_theory/mclennan_tourky.py
- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/random.py
- quantecon/gridtools.py
- quantecon/markov/core.py
- quantecon/markov/ddp.py
- quantecon/markov/random.py
- quantecon/quad.py
- quantecon/random/utilities.py
fixes #287 
Fix unknown sections.
> WIP: fix doc warnings

- .coveragerc
This PR adjusts the coverage rc file to adopt custom regex exclusions to make ``coverage`` statistics more useful in diagnosing code that isn't covered by tests. 
This will help with PR #302
> adjust coveragerc to skip @jit functions

- quantecon/lqcontrol.py
- quantecon/tests/test_lqcontrol.py
This PR
- implements changes to ``lqcontrol.py`` from PR #157 (without old version changes). 
the only variation is to continued use of ``w_path`` rather than ``w_t`` used in PR #157
> implement changes from PR #157 to fix lqcontrol docstring

- quantecon/estspec.py
- this PR removes the ols import from pandas, which has been deprecated in pandas v0.2 and is causing the quantecon package to break
- I've used the statsmodels time series module to estimate the ar1
- I was using the lecture solutions to test the code, but this includes a simulation so I can't exactly replicate the output - would someone be able to check this gives correct results?
- I'm not sure why Newey-West covariance matrix is used, but I've included it
> fix compatibility with pandas v0.2

- docs/source/util.rst
- docs/source/util/numba.rst
- quantecon/game_theory/support_enumeration.py
- quantecon/game_theory/tests/test_support_enumeration.py
- quantecon/util/numba.py
- quantecon/util/tests/test_numba.py
* It turned out that the workaround in item 3 in https://github.com/QuantEcon/QuantEcon.py/pull/263#issue-178525924 did not work properly in all cases.
* This fix replaces "SVD + linalg.solve" with `_numba_linalg_solve`, which calls directly Numba internal `numba_xgesv`.
* As a bonus, this leads to about 9x speedup.
```py
ns = [8, 9, 10, 11]
seed = 1234
for n in ns:
g = gt.random_game((n, n), random_state=seed)
%timeit gt.support_enumeration(g)
```
* Current version:
* n = 8: `99.1 ms`
* n = 9: `391 ms`
* n = 10: `1.58 s`
* n = 11: `6.56 s`
* This PR:
* n = 8: `11.6 ms`
* n = 9: `43 ms`
* n = 10: `179 ms`
* n = 11: `727 ms`
```py
numba.__version__
'0.30.1'
```
> FIX: support_enumeration: Use `_numba_linalg_solve`

- quantecon/arma.py
- quantecon/estspec.py
- quantecon/ivp.py
- quantecon/kalman.py
- quantecon/lae.py
- quantecon/lqcontrol.py
- quantecon/lss.py
- quantecon/markov/approximation.py
- quantecon/matrix_eqn.py
- quantecon/quadsums.py
- quantecon/robustlq.py
Sorry about such a large commit (did not expect to fix this much)
A lot of math renderings weren't working either due to:
- no use of .. math::
- not using raw string
- not using '\\' for symbols
- matrices formatted incorrectly
Also
- ivp.py's class docstring was placed incorrectly
- I deleted some whitespaces and cleaned up some code/comments
- there were a couple of errors(?) related to matrix conformability
- fixed a compilation warning message from approximation.py
Best way to review is probably to `make html` in quantecon/docs
> Fix math rendering in docstrings

- quantecon/util/notebooks.py
this addresses issue #278.
When writing this, the default values set for this utility are probably no longer appropriate with the development of ``QuantEconLib``. I propose to remove these defaults to make this utility a bit more general as a simple way of fetching files from a Github repo. 
```python
REPO = "https://github.com/QuantEcon/QuantEcon.notebooks"
RAW = "raw"
BRANCH = "master"
FOLDER = "dependencies"          #Hard Coded Dependencies Folder on QuantEcon.notebooks
```
> add some examples for the documentation on the nb_fetch utility

- quantecon/markov/ddp.py
- quantecon/markov/tests/test_ddp.py
Sometimes I find it helpful to have convenient, even if not optimally efficient, routines for converting between the SA and full formulations. 
This PR implements such routines.
> ENH: added routines to convert ddp between full and SA formulations

- quantecon/arma.py
- quantecon/discrete_rv.py
- quantecon/distributions.py
- quantecon/ecdf.py
- quantecon/game_theory/normal_form_game.py
- quantecon/graph_tools.py
- quantecon/kalman.py
- quantecon/lae.py
- quantecon/lqcontrol.py
- quantecon/lss.py
- quantecon/markov/core.py
- quantecon/markov/ddp.py
- quantecon/robustlq.py
This PR changes the class style (issue: jstac/QuantEcon.lectures#497).
Specifically, the PR changes `class Foo(object):` to `class Foo:`.
Note: `object` used to be required to provide some class infrastructure like `super` and `@property` in `python2.7` which is no longer required in `python3.X` as inheritance of these things are now implicit.
> Fix class style

- quantecon/util/timing.py
``tac`` and ``toc`` docstrings were incorrect. 
fixes #314
> fix timing utility docstrings for tic toc tac

- quantecon/tests/test_distributions.py
Adds tests for distributions.py
Close #301
> Tests for distributions.py

- quantecon/game_theory/lemke_howson.py
- quantecon/game_theory/tests/test_lemke_howson.py
Added tests for exceptions to lemke_howson.py and raise type error when init_pivot type is not an integer instance.
Fix #302
> Test lemke howson exceptions

- docs/source/game_theory.rst
- docs/source/game_theory/vertex_enumeration.rst
- quantecon/game_theory/__init__.py
- quantecon/game_theory/tests/test_vertex_enumeration.py
- quantecon/game_theory/vertex_enumeration.py
Implement "vertex enumeration", using [scipy.spatial.ConvexHull](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html) to compute convex hull, or facet enumeration, of the polars of the (translated) best response polytopes.
* This is faster than `support_enumeration`:
```py
ns = [10, 11, 12]
seed = 1234
for n in ns:
g = gt.random_game((n, n), random_state=seed)
%timeit gt.support_enumeration(g)
%timeit gt.vertex_enumeration(g)
```
* `support_enumeration`:
* n=10: `124 ms`
* n=11: `528 ms`
* n=12: `2.17 s`
* `vertex_enumeration`:
* n=10: `8.95 ms`
* n=11: `21.8 ms`
* n=12: `64.4 ms`
* For some degenerate games, `vertex_enumeration` finds all the extreme equilibria, while `support_enumeration` fails:
```py
g = gt.NormalFormGame(
[[(3, 3), (3, 3)],
[(2, 2), (5, …
```
> game_theory: Add vertex_enumeration

- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/tests/test_normal_form_game.py
* If `method=None`, `quantecon.game_theory. lemke_howson ` is used, while if `method='simplex'`, `scipy.optimize.linprog` is used with `method='simplex'`.
* [For a future PR] Accept `method='interior-point'` once scipy/scipy#7123 gets released.
> game_theory.Player: Add is_dominated

- quantecon/util/tests/test_timing.py
`test_tic_tac_toc` sometimes fails on my machine. Change absolute tolerance to relative tolerance.
> FIX: Use relative tolerance in test_tic_tac_toc

- quantecon/arma.py
- quantecon/tests/test_arma.py
Address #153
As a first step, here are some changes adding a random_state option to arma.py (issue #153). If the approach is appropriate, I have already written the code for the other remaining files.
> FEAT: Add random_state option (issue #153)

- quantecon/tests/test_gridtools.py
Run `nosetests -a '!slow'` to run  tests that do NOT have the attribute `slow`
See https://github.com/QuantEcon/QuantEcon.py/issues/109#issuecomment-323249871
> TEST: Set 'slow' on slow tests in test_gridtools.py

- quantecon/util/__init__.py
- quantecon/util/tests/test_timing.py
- quantecon/util/timing.py
Here are some improvements for `.tic`, `.tac`, `.toc`, as well as a new function `loop_timer` for running loops like `%timeit`.
Close #322
> FEAT: New features for timing functions (Issue #322)

- quantecon/markov/core.py
The definition was not matching the code.
> DOC: Fix a math definition in docstring

- .coveragerc
- quantecon/__init__.py
- quantecon/gridtools.py
- quantecon/tests/test_gridtools.py
From my old code https://github.com/oyamad/simplex_grid.
To be used in `game_theory`.
> Add simplex_grid and simplex_index

- quantecon/game_theory/tests/test_mclennan_tourky.py
- quantecon/game_theory/tests/test_support_enumeration.py
- quantecon/game_theory/tests/test_vertex_enumeration.py
Adds tests to increase the coverage on game_theory
> TEST: Increase coverage on game_theory

- quantecon/discrete_rv.py
- quantecon/lqcontrol.py
- quantecon/lqnash.py
- quantecon/lss.py
- quantecon/quad.py
- quantecon/tests/test_discrete_rv.py
- quantecon/tests/test_lqcontrol.py
- quantecon/tests/test_lqnash.py
- quantecon/tests/test_lss.py
- quantecon/tests/test_quad.py
Adds a random_state option to the remaining files mentioned in issue #153. I haven't added a test for lqnash.py yet -- @cc7768 did you have something in mind to add to this file? 
Close #153
> FEAT: Add option to supply a random seed (issue #153)

- quantecon/robustlq.py
- quantecon/tests/test_robustlq.py
Adds the following case:
If Q and B are zero matrices, RBLQ assumes that the user wants to solve a "pure forecasting problem" defined on p171 in Robustness (Hansen and Sargent, 2008).
It is assumed that the user sets up the problem in a way that "eliminates" F.  This involves redefining the R and A matrices in equations (1) and (2) (of [this lecture](https://lectures.quantecon.org/py/robustness.html)) as 
R_adj = R + F'QF 
A_adj = A - BF
Then, using R_adj, A_adj, C with Q=B=0 (zero matrices), RBLQ returns a K which is the worst-case with respect to the proposed policy F.
> RBLQ: add pure forecasting case 

- quantecon/matrix_eqn.py
Fix #84
Followed https://github.com/QuantEcon/QuantEcon.py/issues/84#issuecomment-59520535, where I chose `1/(machine epsilon)` for `BIGNUMBER`.
> FIX: Replace `np.isfinite(cn)` with `cn * EPS < 1` in solve_discrete_riccati

- quantecon/quad.py
This just jits the 1-dimensional quadrature routines.
The multi-dim ones are implemented using higher order functions, so they still will not work in nopython mode.
> ENH: jit the 1d quadrature routines

- quantecon/matrix_eqn.py
- quantecon/tests/test_robustlq.py
> FIX: Remove 0.0 from `candidates` in `solve_discrete_riccati`

- quantecon/lqcontrol.py
- quantecon/matrix_eqn.py
- quantecon/tests/test_lqcontrol.py
- quantecon/tests/test_ricatti.py
> Riccati: Add option to use scipy.linalg.solve_discrete_are

- setup.py
One nice feature is ability to use ``python setup.py develop``. 
This sets up a link between ``cwd`` and ``site-packages`` for ``install`` and enables quick testing etc.
> add ability to use setuptools in preference to distutils.core

- quantecon/__init__.py
- quantecon/graph_tools.py
- quantecon/tests/test_graph_tools.py
To be (possibly) used in `game_theory`.
> Add random_tournament_graph

- quantecon/gridtools.py
Use `scipy.special.comb` instead of `scipy.misc.comb` as `scipy.misc.comb` is deprecated in scipy 1.0.0.
> FIX: Update `num_compositions`

- quantecon/gridtools.py
- quantecon/tests/test_gridtools.py
- quantecon/util/numba.py
- quantecon/util/tests/test_numba.py
1. Add `comb_jit`, Numba jit version of `scipy.special.comb`
Returns `0` if the outcome exceeds the maximum value of `np.intp`
2. Add `num_compositions_jit` which uses `comb_jit`
3. Compile `simplex_grid` in nopython mode using `num_compositions_jit`
> Add Numba jit version of scipy.special.comb

- quantecon/game_theory/support_enumeration.py
- quantecon/util/combinatorics.py
- quantecon/util/tests/test_combinatorics.py
1. Re-implement `next_k_array` which is now based on "Algotirhm T" in [Generating All Combinations](http://www.kcats.org/csci/464/doc/knuth/fascicles/fasc3a.pdf) by Knuth.
2. Add `k_array_rank` and `k_array_rank_jit`:
* `k_array_rank` works with pure Python's arbitrary precision integer.
* `k_array_rank_jit` is Numba jit compiled and limited by the range of `np.intp`.
3. `_next_k_array` in `support_enumeration` is replaced by the new `next_k_array`:
* The previous `_next_k_array` is implemented by "Gosper's hack" (see https://github.com/QuantEcon/QuantEcon.py/pull/263#issue-178525924) which has a limit in the size of the input array by the number of bits of `np.int`.
* The new `next_k_array` has no such limitation.
* The performance does not change almost at all.
> Re-implement `next_k_array`; add `k_array_rank`

- quantecon/game_theory/pure_nash.py
- quantecon/game_theory/tests/test_pure_nash.py
> pure_nash_brute: Add tol option

- .travis.yml
- docs/qe_apidoc.py
- quantecon/models/__init__.py
- setup.py
the ``models`` subpackage was removed in ``0.3`` and a deprecation warning added. This  PR now completely removes the ``models`` subpackage as ``QuantEcon.applications`` no longer exists, and is not supported. 
I have left the ``models`` infrastructure in ``qe_apidoc.py`` in case it is required in the future. It was a way of organising the docs into ``tools`` and ``models`` headings.
``travis.yml`` has been updated to remove the ignore on models.
> remove models subpackage from QuantEcon.py

- quantecon/game_theory/support_enumeration.py
Use `NormalFormGame.payoff_arrays` (#382)
> support_enumeration: Refactoring

- quantecon/util/tests/test_timing.py
- quantecon/util/timing.py
>  Fix tac, toc, loop_timer to return float

- quantecon/graph_tools.py
- quantecon/markov/core.py
Replace `matrix[indices, :][:, indices]` with `matrix[np.ix_(indices, indices)]`.
I happened to find [this fact](https://stackoverflow.com/questions/4257394/slicing-of-a-numpy-2d-array-or-how-do-i-extract-an-mxm-submatrix-from-an-nxn-ar#comment4623697_4257708).
> MAINT: Use `np.ix_` to extract submatrix

- quantecon/__init__.py
- quantecon/discrete_rv.py
- quantecon/tests/test_discrete_rv.py
Adds a jitted function for drawing discrete random variables. Note that `DiscreteRV.draw` no longer uses `check_random_state` as Numba supports top-level functions from the numpy.random module, but does not allow you to create individual RandomState instances.
Close #390
> FEAT: Add jitted function for drawing

- quantecon/kalman.py
As specified in https://github.com/QuantEcon/QuantEcon.py/issues/367#issue-268592941
> Implement Sigma_infinity and K_infinity as properties

- quantecon/__init__.py
- quantecon/discrete_rv.py
- quantecon/random/__init__.py
- quantecon/random/tests/test_utilities.py
- quantecon/random/utilities.py
- quantecon/tests/test_discrete_rv.py
Close #393.
(Also revert the changes by #391, as we should not have both `random_choice` and `random.draw`.)
> FEAT: Add random.draw

- docs/qe_apidoc.py
- docs/source/game_theory.rst
- docs/source/game_theory/game_generators/bimatrix_generators.rst
- docs/source/util.rst
- docs/source/util/combinatorics.rst
- quantecon/game_theory/__init__.py
- quantecon/game_theory/game_generators/__init__.py
- quantecon/game_theory/game_generators/bimatrix_generators.py
- quantecon/game_theory/game_generators/tests/test_bimatrix_generators.py
- setup.py
For the background, see https://github.com/QuantEcon/Games.jl/issues/53#issue-260613877. Cc: @ptigwe
> Add sample game generators from bimatrix-generators

- CHANGELOG.md
This PR looks at: https://github.com/skywinder/github-changelog-generator to see if it can be used to auto-generate a ``CHANGELOG.md`` file. 
Fixes #402
> Setup an auto-generate changelog for releases

- setup.py
This PR adds ``0.36.2`` as a minimum numba version required for installation in ``setup.py``
``numba`` is one of the key dependencies for QuantEcon.py. Given our user base -- it may be helpful to alternatively write a version check in the base ``__init__.py`` file which would give us the opportunity to issue a more useful error message based on ``conda``.
Could check if ``numba.__version__ > minimum value`` otherwise print out instructions to upgrade such as ``conda install numba=0.37``.  Any comments welcome.
> add minimum version number for numba support

- quantecon/tests/test_discrete_rv.py
Fix the test failure occurring with the latest Anaconda 5.2.0.
> TEST: Fix test_discrete_rv

- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/tests/test_normal_form_game.py
- setup.py
```py
import quantecon.game_theory as gt
player = gt.Player(
[[-1, 1],
[1, -1],
[-0.5, -0.5]]
)
player.dominated_actions()
```
```py
[2]
```
```py
player.is_dominated(2, method='interior-point')
```
```py
True
```
> Add `'interior-point'` option to `is_dominated`; add `dominated_actions`

- quantecon/game_theory/tests/test_vertex_enumeration.py
- quantecon/game_theory/vertex_enumeration.py
For *some* degenerate games, `qhull_options='QJ'` helps to identify all the Nash equilibria:
```py
bimatrix = [[(0, 3), (6, 1)],
[(2, 2), (5, 6)],
[(3, 3), (3, 3)]]
g = gt.NormalFormGame(bimatrix)
```
```py
gt.vertex_enumeration(g)
```
```py
[(array([0.66666667, 0.33333333, 0.        ]),
array([0.33333333, 0.66666667]))]
```
```py
gt.vertex_enumeration(g, qhull_options='QJ')
```
```py
[(array([0., 0., 1.]), array([1., 0.])),
(array([0.0000000e+00, 3.9409863e-11, 1.0000000e+00]),
array([0.66666667, 0.33333333])),
(array([0.66666667, 0.33333333, 0.        ]),
array([0.33333333, 0.66666667]))]
```
but not always:
```py
g = gt.NormalFormGame((2, 2))  # payoffs all zero
```
```py
gt.vertex_enumeration(g)
```
```py
[(array([1., 0.]), array([1., 0.]))]
```
```py
gt.vertex_enumeration(g, …
```
> EHN: Add `qhull_options` to `game_theory.vertex_enumeration`

- quantecon/optimize/__init__.py
- quantecon/optimize/root_finding.py
- quantecon/optimize/tests/test_root_finding.py
Hi @jstac, in this PR @spvdchachan and I added in the Jitted Newton methods for root finding, In particular, the `newton` method and the `newton_secant` method. Additionally, we wrote some test cases too.
As several people mentioned in #416 , extra information about convergence, iterations, etc. is crucial.
Therefore, we provided this extra information but instead used the `namedtuple` collection for fields to be accessed easier through names rather than numerical indexes in normal tuples.
We followed the source code directly from Scipy but there were several technical issues with Numba.
- Optional function args: Numba only supports optional parameters of primitive types only. Also, it is not guaranteed to be 100% stable as well (explicitly mentioned in the doc). This means it is not …
> ENH: Root finding

- quantecon/optimize/__init__.py
- quantecon/optimize/root_finding.py
- quantecon/optimize/tests/test_root_finding.py
Hi @jstac and @mmcky 
I would like to resolve #422 in this PR.
I've added two new robust root finding methods `bisect` and `brentq` which are based on Scipy's version.
These procedures were written in C originally and I rewrote them in Python to jit compile.
> Add bisection and brent's method for root finding

- docs/source/tools.rst
- docs/source/tools/dle.rst
- quantecon/__init__.py
- quantecon/dle.py
- quantecon/tests/test_dle.py
This PR adds `DLE` object for solving dynamic linear economic problems by converting to LQ problem.  This code has been contributed by Sebastian Graves. 
Adjustments required for inclusion in `QuantEcon.py`:
> add solver for dynamic linear economies as LQ problem

- quantecon/optimize/root_finding.py
Fixes the documentation of `newton`, `newton_halley` and `newton_secant`.
> DOC: Fix the doc of `root_finding.py` to display nicely

- quantecon/game_theory/support_enumeration.py
Fix #434
Note that `np.arange(k, dtype=np.int_)` does not work in `nopython` mode; see https://github.com/numba/numba/issues/2643#issuecomment-363472901.
> FIX: Force tuple elements to have the same dtype

- quantecon/robustlq.py
- quantecon/tests/test_robustlq.py
>  Add method option in robustlq.py

- quantecon/kalman.py
This PR fixes issue #411 which points out a minor inconsistency on the docstring of ``x_hat``, the mean vector of ``Kalman``.
> Fix docstring of x_hat in Kalman class

- quantecon/__init__.py
- quantecon/inequality.py
- quantecon/tests/test_inequality.py
First stab at creating inequality indices, as discussed in #395 
Tests added and  `nosetests` passed.
> Added basic inequality mesasures: lorenz curve and gini

- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/tests/test_normal_form_game.py
Example:
```py
g = gt.NormalFormGame([[(3, 0), (0, 1)], [(0, 0), (3, 1)], [(1, 1), (1, 0)]])
print(g)
```
```
2-player NormalFormGame with payoff profile array:
[[[3, 0],  [0, 1]],
[[0, 0],  [3, 1]],
[[1, 1],  [1, 0]]]
```
```py
nums_actions_deleted = np.zeros(g.N)
step = 0
while True:
for i in range(g.N):
actions = g.players[i].dominated_actions()
g = g.delete_action(i, actions)
if len(actions) > 0:
step += 1
print('Step {step}'.format(step=step))
print(g, '\n')
nums_actions_deleted[i] = len(actions)
if nums_actions_deleted.prod() == 0:
break
```
```
Step 1
2-player NormalFormGame with payoff profile array:
[[[3, 0],  [0, 1]],
[[0, 0],  [3, 1]]] 
Step 2
2-player NormalFormGame with payoff profile array:
[[[0, 1]],
[[3, 1]]] 
Step 3
2-player NormalFormGame with payoff profile array:
[[[3, …
```
> Add Player.delete_action, NormalFormGame.delete_action

- quantecon/optimize/__init__.py
- quantecon/optimize/multivar_maximization.py
- quantecon/optimize/nelder_mead.py
- quantecon/optimize/tests/test_multivar_max.py
- quantecon/optimize/tests/test_nelder_mead.py
Adds a jitted implementation of the Nelder-Mead algorithm for multivariate optimization. 
The two main references are [Lagarias et. al (1998)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.120.6062&rep=rep1&type=pdf) for the algorithm and [Singer and Singer (2004)](https://onlinelibrary.wiley.com/doi/abs/10.1002/anac.200410015) for efficiency. 
It might be a good idea to have a common interface for `scalar_maximization.py` and this multivariate version. Please let me know if you have any suggestions for setting up this interface and choosing 
names.
```python
import quantecon as qe
from numba import njit
import numpy as np
@njit
def rosenbrock(x):
return -(100 * (x[1] - x[0] ** 2) ** 2 + (1 - x[0])**2)
x0 = np.array([-2, 1]) 
```
```python
qe.optimize.maximize(rosenbrock, x0, …
```
> FEAT: Add the Nelder-Mead algorithm

- quantecon/game_theory/__init__.py
- quantecon/game_theory/repeated_game.py
- quantecon/game_theory/tests/test_repeated_game.py
A Python version implementation of AS (Abreu and Sannikov 2014) algorithm. (Julia version is QuantEcon/Games.jl#65).
Comparing to the Julia version, the running time is significantly reduced here by using `scipy.spatial.ConvexHull`. On my computer, the example from AS runs for 30 ms on average, which is even quicker than the original Java implementation (usually runs for 50 ms, sometimes more than 100 ms). (Downloadable from [here](http://econtheory.org/supp/1302/supplement.zip))
A [demonstration](https://nbviewer.jupyter.org/github/shizejin/Notebooks/blob/master/AS%20algorithm-Python.ipynb) shows the AS example and Prisoner's dilemma example.
Detailed docstring needed to be added. Will see if it's possible to improve the efficiency further.
> ENH: Add AS algorithm.

- .travis.yml
- quantecon/util/tests/test_timing.py
> Travis: Add macOS to the build matrix

- quantecon/game_theory/tests/test_pure_nash.py
Fix [this warning](https://travis-ci.org/QuantEcon/QuantEcon.py/jobs/465847870#L977) in `test_pure_nash`.
> Fix warning in test_pure_nash

- quantecon/optimize/scalar_maximization.py
- quantecon/optimize/tests/test_scalar_max.py
Adds error messages for invalid inputs for `brent_max`.
Close #442
> ENH: Add errors for invalid inputs for `brent_max`

- .travis.yml
They should be run only from time to time, e.g. between releases, or
when the commit specifically states the perf modification of the
relevant code.
This fixes #109.
> Travis: Disable performance tests

- quantecon/arma.py
- quantecon/quad.py
- quantecon/random/utilities.py
- quantecon/util/notebooks.py
This ~partially addresses~ fixes #449. The `import quantecon` time on my machine decreases from ~5.4s to ~4.6s~ to ~1s.
> quad: Import sympy only when necessary

- .travis.yml
- quantecon/discrete_rv.py
- quantecon/tests/util.py
> Travis: Move dependency installs with wheels available to pip

- quantecon/optimize/nelder_mead.py
Fixes the example in the documentation of `nelder-mead`.
> DOC: Update example for `nelder_mead`

- .travis.yml
- quantecon/__init__.py
- quantecon/arma.py
- quantecon/game_theory/__init__.py
- quantecon/game_theory/game_generators/__init__.py
- quantecon/game_theory/tests/test_repeated_game.py
- quantecon/markov/__init__.py
- quantecon/markov/random.py
- quantecon/markov/tests/test_approximation.py
- quantecon/markov/tests/test_random.py
- quantecon/optimize/__init__.py
- quantecon/optimize/scalar_maximization.py
- quantecon/random/__init__.py
- quantecon/tests/__init__.py
- quantecon/tests/test_arma.py
- quantecon/tests/test_dle.py
- quantecon/tests/test_filter.py
- quantecon/tests/test_gridtools.py
- quantecon/tests/test_kalman.py
- quantecon/tests/test_lqcontrol.py
- quantecon/tests/test_lqnash.py
- quantecon/tests/test_lss.py
- quantecon/tests/test_matrix_eqn.py
- quantecon/tests/test_quadsum.py
- quantecon/tests/test_rank_nullspace.py
- quantecon/tests/test_robustlq.py
- quantecon/util/__init__.py
- quantecon/util/array.py
- quantecon/util/notebooks.py
- quantecon/util/tests/test_timing.py
Detected via `flake8 quantecon | grep F401 | grev -v __init__`.
> Fix all F401 unused imports

- quantecon/lss.py
- quantecon/tests/test_lss.py
Currently:
```python
A = np.zeros((1, 2))
C = np.zeros((1, 1))
G = np.zeros((1, 1))
qe.LinearStateSpace(A, C, G)
```
raises
```
TypeError: not all arguments converted during string formatting
```
This PR fixes `lss.py` so that the correct error is raised when `A` is not a square matrix.
> FIX: Raise correct error when `A` is not square in `LinearStateSpace`

- quantecon/random/utilities.py
> Fix `sample_without_replacement` using guvectorize

- quantecon/markov/approximation.py
- quantecon/markov/tests/test_approximation.py
Try to make `markov.tauchen` able to handle non-zero drift term in the AR(1) process.
[Here](https://nbviewer.jupyter.org/github/shizejin/Notebooks/blob/master/AR%281%29%20with%20drift%20term.ipynb) discusses the logic of modification made.
> Add drift term keyword to `markov.tauchen`.

- CHANGELOG.md
- README.md
- quantecon/version.py
- setup.py
See CHANGELOG and README for details.
> Release of version 0.4.4

- docs/source/conf.py
- quantecon/optimize/scalar_maximization.py
See #460.
Just removed `matplotlib.sphinxext.only_directives` in `docs/source/conf.py`. It works fine on my environment with Anaconda.
> FIX: DOC: Remove `matplotlib.sphinxext.only_directives`

- .travis.yml
Only submit coverage reports from the `linux` build job.
> TRAVIS: Set coverage branch as `linux`.

- quantecon/markov/tests/test_approximation.py
> FIX: Increase `tol` in `rouwenhorst` test.

- quantecon/__init__.py
- quantecon/lqcontrol.py
- quantecon/matrix_eqn.py
- quantecon/tests/test_lqcontrol.py
Integrating the code for solving Markov jump LQ dynamic programming problems from the [notebook](https://github.com/QuantEcon/python_lecture_sandpit/blob/master/source/rst/tax_smoothing_1.rst) in the sandpit repository.
The modifications I have made comparing to the original code:
1. modify the notations to be consistent with the existing `LQ` class,
2. discard the usage of `dict` and adopt `ndarray` to store transition, payoff matrices, policies, and value function arrays,
3. arrange the part of matrix calculation to make it easier to read and more efficient.
4. add tests.
[Here](https://nbviewer.jupyter.org/github/shizejin/Notebooks/blob/master/Demonstration%20of%20%60qe.LQ_Markov%60.ipynb) is a demonstration for this `qe.LQ_Markov` class.
Two points that I would like to have your …
> Add `LQMarkov`.

- quantecon/lqcontrol.py
- quantecon/tests/test_lqcontrol.py
I made two fixes  for `LQ` and `LQMarkov` classes.
1. There was a typo in calculating the values of the last period states for `LQMarkov` models. I forgot to left multiply the `C` matrix to the vector of shocks. I have fixed this and modified tests correspondingly.
2. The code was computing stationary values each time we call `compute_series`, which is unnecessary since the optimal policy `F` are stored as class attribute and do not change. This increases running time especially for lectures that simulate multiple paths for the same model, e.g. "How to Pay for a War: Part 1". I modified it to only compute stationary values once when `compute_series` method is called for the first time. By doing so, the running time of "How to Pay for a War: Part 1" decreases from `42s` to `12s`.
The first …
> FIX: two minor modifications in `lqcontrol`

- .travis.yml
This PR updates travis to use `python=3.7` from `python=3.6` as that aligns with the latest `anaconda` distribution release.
> UPD: Update travis to use python=3.7

- quantecon/random/utilities.py
Fix #502
This is a bug of Numba 0.45.0-0.45.1, which has been fixed by numba/numba#4431 on Numba master. It will take some time to be released, so use `random` in place of `random_sample`.
> FIX: random.draw: Replace `random_sample` with `random`

- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/tests/test_normal_form_game.py
Fix #501
Also add `'revised simplex'` method.
> FIX: Player.is_dominated: Fix warnings

- quantecon/ivp.py
- quantecon/lqcontrol.py
- quantecon/tests/test_quad.py
- quantecon/tests/test_robustlq.py
This PR fixes some warnings raised in issues \#505 \#506 and \#507.
1) FutureWarning in `ivp.py` (see issue \#505).
2) RuntimeError in `lq_control.py` (see issue \#506)
3) Pandas related future warnings in `test_quad.py` (see issue \#507).
This is my first QuantEcon PR so let me know if I need to fix anything.
> [FIX] Fix Future Warnings in ivp.py and test_quad.py and RuntimeError in lq_control.py.

- quantecon/__init__.py
- quantecon/inequality.py
Generates a rank size plot from supplied data.  This is quite useful and the code has been written to avoid new external dependences.
No test and I don't have time to write one now.  Would appreciate if we can merge this subject to review and then think about proper tests later.
> Adds a rank size plot to inequality

- README.md
- quantecon/version.py
- setup.py
This PR updates to version `0.4.6`
1. Adds a rank size plot to inequality [\#518](https://github.com/QuantEcon/QuantEcon.py/pull/518) ([jstac](https://github.com/jstac))
1. General cleanup of Package [\#515](https://github.com/QuantEcon/QuantEcon.py/pull/515) ([mmcky](https://github.com/mmcky))
1. \[FIX\] Fix Future Warnings in ivp.py and test\_quad.py and RuntimeError in lq\_control.py. [\#509](https://github.com/QuantEcon/QuantEcon.py/pull/509) ([duncanhobbs](https://github.com/duncanhobbs))
1. FIX: Player.is\_dominated: Fix warnings [\#504](https://github.com/QuantEcon/QuantEcon.py/pull/504) ([oyamad](https://github.com/oyamad))
1. FIX: random.draw: Replace `random\_sample` with `random` [\#503](https://github.com/QuantEcon/QuantEcon.py/pull/503) ([oyamad](https://github.com/oyamad)) …
> update version to 0.4.6

- quantecon/game_theory/game_generators/__init__.py
- quantecon/game_theory/game_generators/bimatrix_generators.py
Address [this alert](https://lgtm.com/projects/g/QuantEcon/QuantEcon.py/snapshot/751d26ba634d53dc76e5fd5766a44e86bb4478d8/files/quantecon/game_theory/__init__.py?sort=name&dir=ASC&mode=heatmap#xfa9fb53073a915c5:1).
> MAINT: bimatrix_generators: Define `__all__`

- quantecon/arma.py
This PR addresses [this](https://lgtm.com/projects/g/QuantEcon/QuantEcon.py/snapshot/b54e85c50aa0535bdea6982134df2936c0805a03/files/quantecon/arma.py?sort=name&dir=ASC&mode=heatmap#xa8bed9b397d1f709:1) lgtm code quality suggestion.
> Fix lgtm warning for arma.py.

- quantecon/quadsums.py
This pull request addresses [this](https://lgtm.com/projects/g/QuantEcon/QuantEcon.py/snapshot/b54e85c50aa0535bdea6982134df2936c0805a03/files/quantecon/quadsums.py?sort=name&dir=ASC&mode=heatmap) lgtm alert.
> Fix lgtm warnings in quadsums.py.

- quantecon/inequality.py
Thanks @jstac and @mmcky . This PR corrects the following typo in the source file of a function ``quantecon.inequality.rank_size_plot`` in the library ``QuantEcon``, please see [here](https://quanteconpy.readthedocs.io/en/latest/_modules/quantecon/inequality.html#rank_size_plot):
- change ``c%`` in the comment ``extract top c%`` to ``(c * 100)%``.
It fixes #543 .
> rank_size_plot_typo

- quantecon/dle.py
This PR addresses [these](https://lgtm.com/projects/g/QuantEcon/QuantEcon.py/snapshot/b54e85c50aa0535bdea6982134df2936c0805a03/files/quantecon/dle.py?sort=name&dir=ASC&mode=heatmap) lgtm alerts for `dle.py`.
> Fix variables never used lgtm warnings in dle.py.

- quantecon/lqcontrol.py
Hi!
For #508 I noticed the solver method matrix_eqn.solve_discrete_riccati_system() allowed for setting an upper bound on the number of iterations, but the stationary_values() method of LQMarkov didn't make use of this arg so it threw an error if it failed to converge within the preset number of iterations, 1000.
I've added an optional arg to the LQMarkov init method to increase the upper bound on the number of iterations, and it was able to converge for the betas mentioned in #508 ( converged for 0.973 in 1001 iterations, for 0.974 in 1050 and for 0.99 in 2700 ).
I didn't add a test for this since this was a small enough change, but I can add it if needed.
> FIX: ValueError `LQMarkov` convergence failed

- quantecon/__init__.py
- quantecon/inequality.py
- quantecon/tests/test_inequality.py
Based on the discussion in #519, refactor the method `rank_size_plot` in `inequality.py` so the output now is the data to be plotted instead of a pyplot `Axes` object. This is in line with the rest of the methods in this module. The method is renamed to `rank_size` to reflect this change.
Also added test for the new method, which checks that
- The `x` and `y` arrays are the same length.
- This length is `(c x 100)%` of the input, as specified.
- The output log-log plot is linear for a Pareto draw, and not otherwise.
Edited the `docstring` for the other two methods in the module for pep8 compliance.
This closes #519
> REF and TEST: rank_size in inequality.py

- quantecon/tests/test_inequality.py
As mentioned in PR #551 the test for `rank_size` method checks for linearity in the output log-log plot. I did this by performing linear regression of `log(size_data)` on `log(rank_data)` and comparing the resulting `r_squared` value to 1.
Turns out an error tolerance of `1e-4` for a sample size of `1000` was a little optimistic. I have increased the sample size to `10000`, reduced the tolerance to `1e-3` and the comparison works as expected now.
Another mistake was setting the seed for exponential draw but not the Pareto draw, I've fixed that as well. I'm not sure if setting a seed here is a good practice in the first place, if not I can remove it and increase sample size / reduce tolerance further.
Please let me know if this is an acceptable fix. This should close #553.
> FIX: rank-size test by inc. sample size

- quantecon/discrete_rv.py
- quantecon/kalman.py
To please lgtm.com. There are lots of usage of `dot` instead of `np.dot` remaining. This PR is just a first step.
> Remove numpy 'import from'

- .github/workflows/test.yml
- quantecon/graph_tools.py
- quantecon/markov/core.py
`fractions.gcd` has been switched to `math.gcd` and is now deprecated in python 3.9.
> FIX: Fix ImportError for `gcd`

- quantecon/lss.py
- quantecon/tests/test_lss.py
Modify the `LinearStateSpace` class with two new features:
1. to compute the steady state covariance matrix by solving a discrete Lyapunov equation rather than "iterating to convergence"
- the `stationary_distributions` now does not take arguments `max_iter` nor `tol`
- when I was trying to apply this new method to some examples, I found that the doubling algorithm does not always work (see more details in #568 ]). Therefore, I am forcing `stationary_distributions` to use the Bartels-Stewart algorithm.
2. adding a method that will compute the stationary covariance matrix
E (y_t - \mu_y) (x_t -\mu_x)' = G \Sigma_x(\infty).
- this is returned as the last output of `stationary_distributions` method
- it is also stored as an field `Sigma_yx`
> Extend `LinearStateSpace` class

- README.md
- quantecon/version.py
- setup.py
**Breaking Changes:**
1. ENH: Extend `LinearStateSpace` class [\#569](https://github.com/QuantEcon/QuantEcon.py/pull/569) ([shizejin](https://github.com/shizejin))
**Other Changes:**
- FIX: [kalman] Always initialize self.Sigma and self.x\_hat [\#562](https://github.com/QuantEcon/QuantEcon.py/pull/562) ([rht](https://github.com/rht))
- TST: Setup Tests via Github Actions [\#561](https://github.com/QuantEcon/QuantEcon.py/pull/561) ([rht](https://github.com/rht))
- ENH: Update root\_finding.py [\#560](https://github.com/QuantEcon/QuantEcon.py/pull/560) ([alanlujan91](https://github.com/alanlujan91))
Special thanks for contributions by [rht](https://github.com/rht), [shizejin](https://github.com/shizejin), [alanlujan91](https://github.com/alanlujan91), and [oyamad](https://github.com/oyamad)
> RELEASE: Setup for Release 0.5.0

- quantecon/lss.py
- quantecon/tests/test_lss.py
This has been left untouched for years...
> MAINT: Use multivariate_normal via random_state

- docs/source/optimize.rst
- docs/source/optimize/minmax.rst
- quantecon/game_theory/normal_form_game.py
- quantecon/optimize/__init__.py
- quantecon/optimize/minmax.py
- quantecon/optimize/tests/test_minmax.py
This PR adds a `minmax` solver to the `quantecon` package. 
This solver is also used by default in `normal_form_game` module in the `is_dominated` method
> EHN: Add minmax solver

- docs/sphinxext/ipython_console_highlighting.py
- docs/sphinxext/ipython_directive.py
- quantecon/compute_fp.py
- quantecon/estspec.py
- quantecon/filter.py
- quantecon/game_theory/pure_nash.py
- quantecon/game_theory/tests/test_vertex_enumeration.py
- quantecon/game_theory/vertex_enumeration.py
- quantecon/lqcontrol.py
- quantecon/lss.py
- quantecon/markov/tests/test_ddp.py
- quantecon/tests/test_ivp.py
- quantecon/util/notebooks.py
There are small typos in:
- docs/sphinxext/ipython_console_highlighting.py
- docs/sphinxext/ipython_directive.py
- quantecon/compute_fp.py
- quantecon/estspec.py
- quantecon/filter.py
- quantecon/game_theory/pure_nash.py
- quantecon/game_theory/tests/test_vertex_enumeration.py
- quantecon/game_theory/vertex_enumeration.py
- quantecon/lqcontrol.py
- quantecon/lss.py
- quantecon/markov/tests/test_ddp.py
- quantecon/tests/test_ivp.py
- quantecon/util/notebooks.py
Fixes:
- Should read `approximation` rather than `approxmation`.
- Should read `response` rather than `reponse`.
- Should read `frequencies` rather than `frequences`.
- Should read `typically` rather than `typicaly`.
- Should read `theorem` rather than `theorm`.
- Should read `symmetric` rather than `symetric`.
- Should read …
> docs: fix a few simple typos

- CHANGELOG.md
- quantecon/version.py
- setup.py
This PR is setting up for release of `v0.5.1` with excellent contributions from @oyamad and @timgates42
> RELEASE: Setup for v0.5.1

- quantecon/game_theory/__init__.py
- quantecon/lqcontrol.py
- quantecon/lqnash.py
- quantecon/matrix_eqn.py
- quantecon/robustlq.py
Hi all! 
This PR addresses the code quality alerts in #466 
Three different things that LGTM picked up in the repo: 
1. An `import *` in quantecon/game_theory/__init__.py. This one was a relatively straightforward fix, just updated with the specific imports required.
2. "wrong number of arguments" in quantecon/util/timing.py. I think this one is a false alarm - there is branching logic to distinguish between the no argument, one argument, and many argument cases. Triggered by a call in TestTicTacToc.test_loop.test_function_one_arg. **Have not made any changes to this code since I believe LGTM is mistaken here.**
3. Module (numpy) is imported with 'import' and 'import from' in a couple different files. This is triggered by an `import numpy as np` followed by `from numpy import dot` etc. …
> LGTM code quality suggestions

- quantecon/game_theory/game_generators/bimatrix_generators.py
- quantecon/random/utilities.py
- quantecon/util/tests/test_numba.py
To remove ``DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`.``
> MAINT: Replace `np.int`

- .github/workflows/conda_ci.yml
- environment.yml
> CI: Add a CI job for testing using conda

- quantecon/ecdf.py
- quantecon/tests/test_ecdf.py
> ENH: Vectorize ECDF's `__call__` method

- .github/workflows/test.yml
- quantecon/game_theory/tests/test_lemke_howson.py
- quantecon/game_theory/tests/test_mclennan_tourky.py
- quantecon/game_theory/tests/test_normal_form_game.py
- quantecon/game_theory/tests/test_pure_nash.py
- quantecon/game_theory/tests/test_random.py
- quantecon/game_theory/tests/test_repeated_game.py
- quantecon/game_theory/tests/test_support_enumeration.py
- quantecon/game_theory/tests/test_vertex_enumeration.py
This PR adds `pytest` testing support for `game_theory`. I will also add a CI job testing using `pytest` for `game_theory`.
Related issue #539
> MAINT, TST: Remove nose imports and use pytest testing

- .github/workflows/conda_ci.yml
- .github/workflows/test.yml
I propose to drop 3.7, as testing against 3.7-3.10 would be too much, and it has been dropped in NumPy.
> TEST: Add Python 3.10, remove 3.7

- .github/workflows/conda_ci.yml
- .github/workflows/test.yml
I propose to exclude windows-latest python-version 3.8, where we often have a failure for `TestTicTacToc.test_timer`.
> TEST: Exclude windows-latest python-version 3.8

- .github/workflows/conda_ci.yml
This should fix the issue with `tagged` releases and `automatic publishing to pypi`
> FIX: issue with publish via tags

- quantecon/markov/tests/test_approximation.py
- quantecon/tests/test_arma.py
- quantecon/tests/test_dle.py
- quantecon/tests/test_kalman.py
- quantecon/tests/test_lqcontrol.py
- quantecon/tests/test_lss.py
- quantecon/tests/test_rank_nullspace.py
- quantecon/tests/test_robustlq.py
- quantecon/util/tests/test_notebooks.py
docs: [teardown_method](https://docs.pytest.org/en/6.2.x/xunit_setup.html#method-and-function-level-setup-teardown)
> [MAINT] TST: Rename `tearDown` to `teardown_method` (pytest fixes)

- docs/qe_apidoc.py
Ref: #606 
Fixes the following error in docs building:
```
Traceback (most recent call last):
File "/Users/thebigbool/repos/QuantEcon.py/docs/qe_apidoc.py", line 341, in <module>
model_tool()
File "/Users/thebigbool/repos/QuantEcon.py/docs/qe_apidoc.py", line 240, in model_tool
tools.remove("version")
ValueError: list.remove(x): x not in list
```
> DOCS: Remove "version" as it was deleted

- quantecon/filter.py
Aside, the docstring also has contradictory content:
> [p] Must be greater than h.
and
> e.g. For quarterly data, h = 8 and p = 4 are recommended.
As such, I haven't added a check to ensure that `p > h`.
> hamilton_filter: Clarify the API

- quantecon/game_theory/brd.py
- quantecon/game_theory/game_generators/bimatrix_generators.py
- quantecon/game_theory/logitdyn.py
- quantecon/game_theory/random.py
- quantecon/game_theory/tests/test_support_enumeration.py
Towards #654
There is absolutely no change in the returns of the code:
```py
>>> random_state = np.random.RandomState(123);
>>> random_state.rand(3)
array([0.69646919, 0.28613933, 0.22685145])
```
```py
>>> random_state = np.random.RandomState(123);
>>> random_state.random_sample(3)
array([0.69646919, 0.28613933, 0.22685145])
```
```py
>>> random_state = np.random.RandomState(123);
>>> random_state.random(3)
array([0.69646919, 0.28613933, 0.22685145])
```
> RFC: Replace `rand()` and `random_sample()` with `random()` in game_theory

- docs/rtd-requirements.txt
- pyproject.toml
- quantecon/arma.py
- quantecon/discrete_rv.py
- quantecon/game_theory/brd.py
- quantecon/game_theory/game_generators/bimatrix_generators.py
- quantecon/game_theory/game_generators/tests/test_bimatrix_generators.py
- quantecon/game_theory/localint.py
- quantecon/game_theory/logitdyn.py
- quantecon/game_theory/normal_form_game.py
- quantecon/game_theory/random.py
- quantecon/game_theory/tests/test_brd.py
- quantecon/game_theory/tests/test_fictplay.py
- quantecon/game_theory/tests/test_localint.py
- quantecon/game_theory/tests/test_logitdyn.py
- quantecon/game_theory/tests/test_normal_form_game.py
- quantecon/game_theory/tests/test_random.py
- quantecon/graph_tools.py
- quantecon/lqcontrol.py
- quantecon/lqnash.py
- quantecon/lss.py
- quantecon/markov/core.py
- quantecon/markov/random.py
- quantecon/quad.py
- quantecon/random/utilities.py
- quantecon/tests/test_inequality.py
- quantecon/tests/test_quad.py
- quantecon/util/__init__.py
- quantecon/util/random.py
Numpy's recommended procedure to generate random numbers now seems to be to use `np.random.Generator` instead of `np.random.RandomState`: https://numpy.org/doc/stable/reference/random/index.html
This PR is to update `check_random_state` to accept `np.random.Generator`, following the corresponding code in scipy:
https://github.com/scipy/scipy/blob/b4a970bf4eba1065ea31f8d0988cd4ec523a07d4/scipy/_lib/_util.py#L174-L203
There are discussions on this at scipy and scikit-learn:
* scipy/scipy#13778
* scikit-learn/scikit-learn#16988
* scikit-learn/scikit-learn#22271
* scikit-learn/scikit-learn#23962
The issue is that some methods are present for `np.random.RandomState` but not for `np.random.Generator`: see the table in [here](https://numpy.org/doc/stable/reference/random/index.html#quick-start). …
> ENH: check_random_state: Accept `np.random.Generator`

- quantecon/gridtools.py
- quantecon/tests/test_gridtools.py
Current code:
```python
>>> nodes = [[0, 1], [2.3, 4.5]]
>>> qe.cartesian(nodes)
array([[0, 2],
[0, 4],
[1, 2],
[1, 4]])
```
This PR:
```python
>>> nodes = [[0, 1], [2.3, 4.5]]
>>> qe.cartesian(nodes)
array([[0. , 2.3],
[0. , 4.5],
[1. , 2.3],
[1. , 4.5]])
```
> FIX: Fix dtype in `cartesian`

- quantecon/markov/approximation.py
- quantecon/markov/tests/test_approximation.py
> Unify `tauchen` and `rouwenhorst` API

- quantecon/__init__.py
> MAINT: Register `cartesian_nearest_index` to __init__

- quantecon/markov/core.py
- quantecon/markov/tests/test_core.py
> FIX: Fix period of reducible MarkovChain with custom state_values

- quantecon/markov/approximation.py
- quantecon/markov/tests/test_approximation.py
https://github.com/QuantEcon/lecture-python.myst/pull/296#issuecomment-1357061603
> Warn only when `n` in not `int` in `tauchen`

- quantecon/markov/__init__.py
- quantecon/markov/estimate.py
- quantecon/markov/tests/test_estimate.py
> Add fit_discrete_mc

- quantecon/__init__.py
- quantecon/markov/tests/test_estimate.py
> Bring estimate_mc into top level namespace

- docs/source/optimize.rst
- docs/source/optimize/lcp_lemke.rst
- quantecon/optimize/__init__.py
- quantecon/optimize/lcp_lemke.py
- quantecon/optimize/linprog_simplex.py
- quantecon/optimize/tests/test_lcp_lemke.py
Solves a linear complementarity problem:
```
z >= 0
w = Mz + q >= 0
zw = 0
```
Straightforward implementation by just combining existing components in `quantecon`.
> ENH: Implement LCP solver

- .github/workflows/ci.yml
Try to fix the error reported in https://github.com/QuantEcon/QuantEcon.py/pull/640#issuecomment-1432213290.
> CI: Workaround for windows

- quantecon/markov/approximation.py
> FIX: Correct docstring of `discrete_var`

- quantecon/_lss.py
To avoid `NumbaDeprecationWarning`
```
NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
```
> RFC: Avoid bare `@jit`

- .coveragerc
- docs/rtd-requirements.txt
- pyproject.toml
- quantecon/_compute_fp.py
- quantecon/random/tests/test_utilities.py
- quantecon/random/utilities.py
- quantecon/util/numba.py
- quantecon/util/tests/test_numba.py
To remove `NumbaDeprecationWarning`
```
NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
```
See
* https://numba.readthedocs.io/en/latest/reference/deprecation.html#deprecation-of-generated-jit
* https://numba.discourse.group/t/replacing-generated-jit-with-overload/1890
> RFC: Replace `@generated_jit` with `@overload`

- CHANGELOG.md
- quantecon/__init__.py
This PR sets up for `v0.7.0` release
fixes #695 
@oyamad tried to get the balance right re: listing the fixes and maintenance in a concise way while highlight the main fixes.
> RELEASE: Setup for v0.7.0

- .github/workflows/ci.yml
> CI: Add testing against Python 3.11

- quantecon/_inequality.py
- quantecon/_kalman.py
- quantecon/_lae.py
- quantecon/bld.bat
- quantecon/build.sh
- quantecon/meta.yaml
Closes    #691 
Removed the following broken links
https://github.com/QuantEcon/QuantEcon.py/blob/8a61df30318a4b2badbff17744782762ee1bac1f/quantecon/_inequality.py#L107-L111
https://github.com/QuantEcon/QuantEcon.py/blob/8a61df30318a4b2badbff17744782762ee1bac1f/quantecon/_kalman.py#L4-L7
https://github.com/QuantEcon/QuantEcon.py/blob/8a61df30318a4b2badbff17744782762ee1bac1f/quantecon/_kalman.py#L57-L60
https://github.com/QuantEcon/QuantEcon.py/blob/8a61df30318a4b2badbff17744782762ee1bac1f/quantecon/bld.bat#L6-L8
https://github.com/QuantEcon/QuantEcon.py/blob/8a61df30318a4b2badbff17744782762ee1bac1f/quantecon/_lae.py#L12-L15
https://github.com/QuantEcon/QuantEcon.py/blob/8a61df30318a4b2badbff17744782762ee1bac1f/quantecon/meta.yaml#L64-L66
> Fix issue #691

- docs/source/conf.py
Fix the build error "HTML 4 is no longer supported by Sphinx": https://readthedocs.org/projects/quanteconpy/builds/20742271/
> FIX: DOC: Remove `html4_writer = True`

- LICENSE
This PR updates the license to `MIT`
> FIX: Update license file from BSD-3 to MIT

- CHANGELOG.md
- quantecon/__init__.py
This PR sets up a new version `v0.7.2`
> RELEASE v.0.7.2

- .github/workflows/ci.yml
This PR upgrades the CI version to setup miniconda and also adds some options to fix the failing CI on macOS.
> Upgrade CI

- README.md
This PR reviews the base level README file and
> MAINT: review README

- quantecon/game_theory/polymatrix_game.py
Similar to that of `NormalFormGame`.
```
>>> g = gt.random_game((2, 3, 4))
>>> g
<2x3x4 3-player NormalFormGame of dtype float64>
>>> polymg = gt.random_polymatrix_game((2, 3, 4))
>>> polymg
<2x3x4 3-player PolymatrixGame>
```
@GautamsGitHub By the way, shall we enforce homogeneous dtype across players in `PolymatrixGame`, as in `NormalFormGame`?
https://github.com/QuantEcon/QuantEcon.py/blob/b733469cae922e7956b23d782054329d464129f7/quantecon/game_theory/normal_form_game.py#L566-L591
> Add __repr__ for PolymatrixGame

- .github/workflows/ci.yml
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
> CI: Update `actions/cache`

- quantecon/markov/tests/test_core.py
- quantecon/tests/test_graph_tools.py
Fix #723
Supersede and close #726
Create `ndarray`s with `dtype=object`, as described in https://github.com/QuantEcon/QuantEcon.py/pull/726#issuecomment-1982612655
> FIX: Fix deprecations in tests

- quantecon/_lqnash.py
Supersede and close #717
Close #349
Refactor as described in https://github.com/QuantEcon/QuantEcon.py/pull/717#issuecomment-1778329873
> Removing randomness from lqnash

- environment_np2.yml
https://numba.discourse.group/t/ann-numba-0-61-0rc2-and-llvmlite-0-44-0rc2-are-out
> CI: Update Numba to 0.61.0rc2

- quantecon/optimize/linprog_simplex.py
> DOC: Add examples to `linprog_simplex`

- docs/Makefile
- docs/README.md
Remove `setup.py` reference from docs
Fixes #757
> DOCS: Remove setup.py reference from docs

- quantecon/game_theory/__init__.py
- quantecon/game_theory/game_converters.py
- quantecon/game_theory/tests/test_game_converters.py
- quantecon/game_theory/tests/test_howson_lcp.py
- quantecon/game_theory/tests/test_polymatrix_game.py
Cc: @GautamsGitHub
A couple of proposals:
1. Alternative implementation of conversion from GAM format: https://github.com/QuantEcon/QuantEcon.py/blob/af6038b8795c1b61c7aa060afbad5badf1e7a090/quantecon/game_theory/game_converters.py#L130-L147
2. Rename `qe_nfg_from_gam_file` to `from_gam`
3. Add `GAMWriter` and `to_gam`
> RFC, ENH: Implement GAMReader and GAMWriter

- CHANGELOG.md
- quantecon/__init__.py
This PR sets up the release of `0.8.0`
@oyamad I thought we would increment to `0.8.0` as there are some `ENH` entries and new features in the change notes. 
Also I propose we use the GitHub release notes mechanism moving forward, rather than using the `CHANGELOG.md` file. Would this be OK? 
I have added a note to `CHANGELOG.md` but let me know if you think we should keep both. Thanks.
> RLS: setup for v0.8.0

- quantecon/game_theory/vertex_enumeration.py
I let ChatGPT read the existing code of [`vertex_enumeration.py`](https://github.com/QuantEcon/QuantEcon.py/blob/main/quantecon/game_theory/vertex_enumeration.py) and got the following suggestion:
* The current [`_vertex_enumeration_gen`](https://github.com/QuantEcon/QuantEcon.py/blob/23a8a9bfd5719ca358d7b9118cd19fad7dc2fe12/quantecon/game_theory/vertex_enumeration.py#L88-L123) has complexity `O(V_0 * V_1)`, where `V_i` is the number of vertices of the best response polytope of player `i`.
* One should use Dict in place of the inner loop, which will reduce the complexity to `O(V_0 + V_1)`.
Benchmarks with random n x n games showed significant speedups, and larger speedups for larger games: about 1.3x faster for n=12, 2x faster for n=14, 15, and 4x faster for n=17. (And no additional …
> RFC: game_theory: Use numba.typed.Dict in `_vertex_enumeration_gen`

- quantecon/__init__.py
This PR sets up for release `v0.8.1`
> RLS: setup for v0.8.1

- quantecon/optimize/lcp_lemke.py
- quantecon/optimize/tests/test_lcp_lemke.py
Fix #768
Bug spotted by Deep Research by ChatGPT o4-mini-high.
(Given the failure reported in #768, I prompted ChatGPT to read the relevant files and identify the bug; it successfully did.)
> FIX: lcp_lemke: Fix bug in first iteration

- quantecon/_matrix_eqn.py
Explicitly pass `e=I` in sp_solve_discrete_are
To be valid also with SciPy 1.16
Fix #771
> FIX: Update `solve_discrete_riccati`

- README.md
> MAINT: Update README.md

- quantecon/__init__.py
This PR sets up `v0.9.0` release. 
I have incremented from `v0.8.2` to `v0.9.0` due to the inclusion of new features such as the Timer.
> RLS: prepare for v0.9.0

- quantecon/__init__.py
This PR prepares for `v0.10.0` that incorporate the latest changes and new feature (timeit)
> RLS: prepare for v0.10.0
