QuantEcon/QuantEcon.py

docs/source/tools.rst
docs/source/tools/cartesian.rst
quantecon/__init__.py
quantecon/gridtools.py
quantecon/tests/test_gridtools.py

Small pull request to close issue #98  .
I haven't changed the files MANIFEST and SOURCES.txt, as I don't know very well how/when they are generated. Do they really need to be versioned ?

REF: renamed cartesian.py as gridtools.py

---

quantecon/common_messages.py

Update warning message if numba import fails

---

quantecon/markov/ddp.py

Add __dir__ to DPSolveResult

---

quantecon/discrete_rv.py

See https://github.com/QuantEcon/QuantEcon.py/pull/213

added asarray in discrete_rv

---

pip-requirements.txt

Add ``requests`` to pip requirements

Updating requirements file

---

.travis.yml

"Note: the Miniconda-latest-\* installers are Miniconda2-\* installers."
(https://repo.continuum.io/miniconda/)

Change Miniconda-latest to Miniconda3-latest

---

quantecon/quad.py

Fix the errors in https://travis-ci.org/QuantEcon/QuantEcon.py/builds/204184130 which block other tests!

BUG: Change floats to ints in _qnwsimp1

---

docs/qe_apidoc.py
docs/source/index.rst

Sorry I forgot to include this in the previous PR.

DOC: Remove descriptions on `models`

---

quantecon/game_theory/support_enumeration.py

Correction according to https://github.com/QuantEcon/Games.jl/pull/26#discussion_r108597600.

DOC: Small correction

---

.coveragerc
quantecon/compute_fp.py
quantecon/tests/test_compute_fp.py

TEST: Add tests for compute_fp.py

---

quantecon/arma.py

removed dep on matplotlib

---

.coveragerc

coveragerc: Add `@generated_jit` and `@guvectorize`

---

quantecon/ce_util.py

Adds docstring for gridmake and _gridmake2.

DOC: Complete docstring for gridmake and _gridmake2

---

quantecon/kalman.py

Needed a new line after an equation

fix kalman class docstring

---

quantecon/game_theory/tests/test_random.py

Test sometimes fails otherwise

TEST: Set atol

---

README.md

I think this is one of the major changes.

Add bugfix PR 364 to Major Changes for v0.3.7

---

quantecon/game_theory/lemke_howson.py
quantecon/game_theory/normal_form_game.py
quantecon/game_theory/tests/test_normal_form_game.py

NormalFormGame: Add `payoff_arrays` attribute

---

docs/source/util.rst
docs/source/util/combinatorics.rst

Forgot to do this for PR #379.

DOC: Generate doc file for util/combinatorics

---

README.md

Add @okuchap to Contributors, who contributed #385.

README: Add a contributor

---

docs/source/optimize.rst
docs/source/optimize/root_finding.rst

DOC: Add doc entry for root_finding

---

quantecon/kalman.py
quantecon/tests/test_kalman.py

Add `method` option in Kalman class.
Close #367

Fix issue#367

---

quantecon/optimize/scalar_maximization.py

I believe we changed the function name a while ago

fix brent_max docstring

---

README.md
quantecon/version.py
setup.py

This PR issues a release for 0.4.2

Release version 0.4.2

---

README.md

Otherwise you can see the pixels.

README: Update coveralls badge to use svg

---

quantecon/inequality.py

Need these arrows for code like rendering

fix for lorenz documentation

---

README.md
quantecon/version.py
setup.py

This PR sets up a new release for version `0.4.3`
See README for changes

Release for version 0.4.3

---

quantecon/optimize/tests/test_scalar_max.py

Fix the names of `brent_max` tests.
Close #452

TEST: Fix the names of tests for `brent_max`

---

doc-requirements.txt

- add matplotlib to environment

FIX: RTD not compiling 

---

quantecon/compute_fp.py
quantecon/estspec.py
quantecon/game_theory/repeated_game.py

Fix some problems reported at https://lgtm.com/projects/g/QuantEcon/QuantEcon.py/alerts?mode=list

Fix alerts by lgtm

---

quantecon/game_theory/__init__.py
quantecon/game_theory/random.py
quantecon/game_theory/tests/test_random.py

Add `random_pure_actions` and `random_mixed_actions`, the pure and mixed action profile generator.
Close #473

FEAT: Add `random_pure_actions` and `random_mixed_actions`

---

quantecon/markov/ddp.py

FIX: Import scipy.sparse.linalg

---

Makefile

remove old test commands from Makefile

---

quantecon/robustlq.py

Fix [this alert](https://lgtm.com/projects/g/QuantEcon/QuantEcon.py/snapshot/f1971f3f9f42f7ada74f2270d3f4d23e0524c248/files/quantecon/robustlq.py?sort=name&dir=ASC&mode=heatmap#L395)

Remove unused variable

---

quantecon/optimize/nelder_mead.py
quantecon/quad.py
quantecon/util/numba.py

FIX: Updates for Numba 0.49.0

---

README.md
quantecon/version.py
setup.py

Release of version 0.4.7

---

quantecon/version.py
setup.py

This PR updates the version number to issue new release `0.4.8`

update version for new release 0.4.8

---

quantecon/version.py
setup.py

Reverts QuantEcon/QuantEcon.py#552

Revert "update version for new release 0.4.8"

---

quantecon/version.py
setup.py

This PR updates version numbers to support release of `quantecon=0.4.8`

update version for new release of 0.4.8

---

quantecon/game_theory/tests/test_random.py

TEST: covariance_game: Increase atol value

---

.github/workflows/test.yml
quantecon/tests/__init__.py
quantecon/tests/util.py

`numba=0.53` has been released: https://numba.discourse.group/t/numba-0-53-0-and-llvmlite-0-36-0-final-release
Close #559

TEST: Add python=3.9

---

docs/source/optimize.rst
quantecon/optimize/linprog_simplex.py

Delete useless docstring for fields of namedtuple

DOC: Edits in docstring for linprog_simplex

---

quantecon/markov/core.py
quantecon/markov/tests/test_core.py

FIX: markov: Respect dtype of P in cdfs

---

CHANGELOG.md
README.md
setup.py

This PR prepares for v0.5.2 release

RELEASE: Preparation for v0.5.2

---

quantecon/game_theory/game_generators/tests/test_bimatrix_generators.py

Replaced with `numpy.testing` functions
Only for `game_theory/game_generators/tests/test_bimatrix_generators.py`
Ref: #539

MAINT: TEST: Remove `nose` functions

---

setup.py

fixes https://github.com/QuantEcon/QuantEcon.py/issues/598
Thanks @oyamad

FIX: Broken links in LONG DESCRIPTION for PyPI

---

.github/workflows/test.yml
quantecon/markov/tests/test_approximation.py
quantecon/markov/tests/test_core.py
quantecon/markov/tests/test_ddp.py
quantecon/markov/tests/test_gth_solve.py
quantecon/markov/tests/test_random.py
quantecon/markov/tests/test_utilities.py

MAINT, TST: Remove nose imports and use pytest

---

docs/rtd-requirements.txt

Fix `readthedocs` error re: `numba`

FIX: update rtd requirements

---

.github/workflows/test.yml
environment.yml
pytest.ini
quantecon/quad.py
quantecon/tests/test_arma.py
quantecon/tests/test_compute_fp.py
quantecon/tests/test_discrete_rv.py
quantecon/tests/test_distributions.py
quantecon/tests/test_dle.py
quantecon/tests/test_ecdf.py
quantecon/tests/test_estspec.py
quantecon/tests/test_filter.py
quantecon/tests/test_graph_tools.py
quantecon/tests/test_gridtools.py
quantecon/tests/test_ivp.py
quantecon/tests/test_kalman.py
quantecon/tests/test_lae.py
quantecon/tests/test_lqcontrol.py
quantecon/tests/test_lqnash.py
quantecon/tests/test_lss.py
quantecon/tests/test_quad.py
quantecon/tests/test_rank_nullspace.py
quantecon/tests/test_ricatti.py
quantecon/tests/test_robustlq.py
quantecon/util/tests/test_array.py
quantecon/util/tests/test_combinatorics.py
quantecon/util/tests/test_notebooks.py
quantecon/util/tests/test_numba.py
quantecon/util/tests/test_timing.py

MAINT: Remove nose imports and use pytest

---

.github/workflows/conda_ci.yml
.github/workflows/test.yml
.gitignore

MAIN: Use official coveralls github action

---

.github/workflows/conda_ci.yml
.github/workflows/test.yml
.gitignore
environment.yml
quantecon/dle.py
quantecon/markov/tests/test_approximation.py
quantecon/markov/tests/test_gth_solve.py
quantecon/tests/test_ivp.py
quantecon/tests/test_ricatti.py

https://github.com/QuantEcon/QuantEcon.py/issues/539#issuecomment-1084615625

MAINT: Fix pytest warnings and use pytest in Conda CI

---

.github/workflows/test.yml
environment.yml

MAINT: Remove statsmodels from dependencies

---

CHANGELOG.md
README.md

MAINT: rework README and move changes to CHANGELOG.txt

---

setup.py

MAINT: remove numba restriction

---

CHANGELOG.md
quantecon/__init__.py

Thanks @Smit-create and @oyamad for all of your contributions to this release
Once this is merge:

RELEASE: v0.5.3

---

quantecon/dle.py

Fix doctring for preferences tuple in dle.py

---

quantecon/game_theory/normal_form_game.py
quantecon/game_theory/tests/test_normal_form_game.py

MAINT: `player.is_dominated`: Allow recent methods for `scipy.optimize.linprog`

---

docs/source/conf.py

FIX: Docs Issue

---

quantecon/util/numba.py

FIX: Update docstring with correct reference

---

quantecon/optimize/tests/test_nelder_mead.py

TEST: Raise atol in test for `optimize.nelder_mead`

---

CHANGELOG.md
quantecon/__init__.py

This PR sets up the package for `v0.6.0` release

RELEASE: v0.6.0

---

quantecon/__init__.py

https://github.com/QuantEcon/QuantEcon.py/pull/682#issue-1516421261

MAINT: Import from _graph_tools, _gridtools

---

quantecon/game_theory/localint.py

FIX: DOC: Remove 2-byte spaces [ci skip]

---

quantecon/lss.py

Fix the empty content issue in the documentation https://github.com/QuantEcon/QuantEcon.py/pull/640#issuecomment-1380153862

FIX: Add __dir__ to lss.py

---

quantecon/random/tests/test_utilities.py
quantecon/random/utilities.py

FIX: random.draw: Add `=None`

---

docs/rtd-requirements.txt

DOC: Pin sphinx<=6.2.1

---

CHANGELOG.md
quantecon/__init__.py

This PR sets up a minor release with bug fixes and improvements to documentation.

RELEASE: Setup v0.7.1

---

.github/workflows/ci.yml
.github/workflows/ci_np2.yml
environment.yml
environment_np2.yml
quantecon/markov/gth_solve.py
quantecon/markov/tests/test_gth_solve.py
quantecon/util/compat.py

Close #734
There is only one error with `NumPy 2.0`, which is fixed by this PR.

FIX: Fix NumPy v2 compatibility issue

---

.github/workflows/ci.yml

CI: Remove redundant step

---

quantecon/tests/test_quad.py

Fixed Pandas warnings in `test_quad.py`

---

.github/workflows/ci_np2.yml

Resolve "`Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)`"
Refer to conda/conda-libmamba-solver#283

CI: Install libmamba from conda-forge

---

quantecon/game_theory/tests/test_utilities.py

MAINT, TST: Remove nose import

---

environment_np2.yml

https://numba.discourse.group/t/ann-numba-0-61-0-llvmlite-0-44-0

CI: Update Numba to 0.61 release version

---

quantecon/game_theory/game_converters.py
quantecon/game_theory/logitdyn.py
quantecon/game_theory/normal_form_game.py

Use unpacking in place of list concatenation.

RFC: game_theory: Minor refactoring

---

quantecon/game_theory/support_enumeration.py

Same as QuantEcon/GameTheory.jl#184

RFC: support_enumeration: Reduce intermediate array creation

---

README.md

This pr adds the stable vs latest badges for python to help the user to understand the project maturity and python compatibility 
Fixes #672 
Changes : 
previous 
After

Fix: Readme to have stable vs latest py badges 

---

docs/source/conf.py

Address https://github.com/QuantEcon/QuantEcon.py/pull/779#pullrequestreview-3036914072

DOC: Fix copyright year

---

quantecon/game_theory/game_converters.py

It shouldn't show up in the documentation.

MAINT: Make `str2num` internal
